services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    command: npm run dev
    restart: always    
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb?schema=public
      - REDIS_URL=redis://redis:6379  # Redis connection string

  prisma-studio:
    image: node:20
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio
    ports:
      - "5555:5555"
    depends_on:
      - db
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
